# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: inflated-goboscript
site_url: https://inflated-goboscript.github.io/
site_description: Documentation for the inflation of gobos.

repo_url: https://github.com/inflated-goboscript/inflator
repo_name: inflated-goboscript/inflator

theme:
  name: material
  custom_dir: overrides

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: amber
      accent: amber

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: amber
      accent: amber

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: amber
      accent: amber


  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - content.code.annotate

plugins:
  - social
  - search
  - glightbox
  - meta

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    # Took this from the goboscript mkdocs yml file
    - icon: fontawesome/brands/github
      link: https://github.com/inflated-goboscript/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/XGKV8X9hfh

  analytics:
    provider: google
    property: G-XXXXXXXXXX  # these are required fields, but unused

    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/inflated-goboscript/inflated-goboscript.github.io/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
            
nav:
  - Home: index.md
  - Inflator:
      - Inflator: inflator/index.md
      - Installation: inflator/installation.md
      - Behaviour: inflator/behaviour.md
      - Usage:
        - Getting Started: inflator/usage/getting started.md
        - Installing Packages: inflator/usage/installing packages.md
